version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
      
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""

    working_directory: ~/circle-ci-playground
    steps:
      - checkout

      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run: 
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"


